[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stayke_contracts = "CHm4RfaJ9y5oeZXKbwLJPsmsktUz5xQjaeYybxVUyQ2n"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
